# Generated by Django 4.2.4 on 2023-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTask2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=200)),
                ('Image1', models.ImageField(upload_to='Pictures1')),
                ('Desc', models.TextField()),
                ('More', models.CharField(max_length=200)),
            ],
        ),
    ]
